In [147]:
#(4주차)

In [2]:
a = 1
b = 2
c = 3
d = 4

a+b, a-b, a*c

print(a+b)
print(a-b)
print(a*c)
print(a*b)
print(d/b)
print(d%c)

3
-1
3
2
2.0
1

In [6]:
a = input()
type(a)

 10

str

In [7]:
a=123
b=-123
c=0
type(a)

int

In [9]:
a=1.2
b=-2.1
type(a)

float

In [11]:
a = 1.24e-2
a

0.0124

In [12]:
b=1.24E2
b

124.0

In [13]:
10<15

True

In [14]:
10>15

False

In [16]:
print("=" *50)
print("My Program")
print("=" *50)

==================================================
My Program
==================================================

In [1]:
A = [1, 2, 3, 4, 5]
type(A)

B = [1, 2, 3, 4, 5]
type(B)

list

In [19]:
a = "독고영재, 50"
b = "김철수, 30"
people = [a, b]
people

['독고영재, 50', '김철수, 30']

In [20]:
A = [10, 20, 30]
B = (10, 20, 30)
A, B

([10, 20, 30], (10, 20, 30))

In [33]:
import numpy as np

a=np.array([1,2,3])
b=np.array([5,6,7])
c=a+b
d=b+a
c.shape
print(c)
print(d)
type(c)

[ 6  8 10]
[ 6  8 10]

numpy.ndarray

In [32]:
a=[1,2,3]
b=[5,6,7]
a+b

[1, 2, 3, 5, 6, 7]

In [42]:
D = [1,2,4,"a"]
E = np.array(D)

print(D)
print(E)
D*2

[1, 2, 4, 'a']
['1' '2' '4' 'a']

[1, 2, 4, 'a', 1, 2, 4, 'a']

In [40]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[5,6,7],[8,9,10]])
c=a+b
c.shape

(2, 3)

In [41]:
a = [1,2]
a*2

[1, 2, 1, 2]

In [46]:
a = [1,5,7,8,10,"안녕","a"]



print(h)


print("-" * 50)
print("데이터전처리 수업")
print("끝")
print("=" * 50)

[1 2 4 5 2 3 5 6]
[21 21 21 21 21 21]
--------------------------------------------------
데이터전처리 수업
끝
==================================================

In [49]:
b = [1,2,4,5]
c=[2,3,5,6]
h=np.array(b)
i=np.array(c)
j=h+i

array([ 3,  5,  9, 11])

In [52]:
d=np.array([[1,2,3,4,5,6], [20,19,18,17,16,15]])
d

array([[ 1,  2,  3,  4,  5,  6],
       [20, 19, 18, 17, 16, 15]])

In [146]:
#(5주차)

In [7]:
A = "안녕하세요 지금은 데이터 전처리 수업 시간입니다."
A[0:5]

'안녕하세요'

In [8]:
A[-5:]

'간입니다.'

In [12]:
A[-6:-4]

'시간'

In [14]:
A[21:23]

'시간'

In [17]:
print("안녕하세요\n반갑습니다")

안녕하세요
반갑습니다

In [19]:
A = "당신의 영어 성적은 {}점입니다. 그리고 수학 성적은 {}점입니다."
A.format(100,100)

'당신의 영어 성적은 100점입니다. 그리고 수학 성적은 100점입니다.'

In [23]:
print(("{:.2f},{:.3f}").format(3.1415,3.1415))

3.14,3.142

In [27]:
url = "https://www.naver.com/"
str = url.replace("https://","")
print(str)

www.naver.com/

In [33]:
A = ["독고영재, 50", "김철수,30"]
A[0][0:4]

'독고영재'

In [39]:
a="독고영재,50" 
a[:a.index(",")]

'독고영재'

In [40]:
b="김철수,30"
b[:b.index(",")]

'김철수'

In [45]:
a = ["독고영재, 50", "김철수,30"]
b = ["김철수, 20", "김영희,25"]
a[0][:a[0].index(",")]

'독고영재'

In [47]:
a = ["독고영재, 50", "김철수,30"]
b = ["김철수, 20", "김영희,25"]
b[1][:b[1].index(",")]

'김영희'

In [50]:
a=["hi", 10, "80", "김철수", 50, 50.6]
type(a[1])

int

In [51]:
type(a[3])

str

In [52]:
type(a[5])

float

In [54]:
a=["hi", 10, "80", "김철수", 50, 50.6]
a.append(1)
a

['hi', 10, '80', '김철수', 50, 50.6, 1]

In [56]:
a.pop(1)
a

['hi', '김철수', 50, 50.6, 1]

In [58]:
a=["hi", 10, "80", "김철수", 50, 50.6]
a.index(50)
a.pop(4)
a

['hi', 10, '80', '김철수', 50.6]

In [63]:
a=["hi", 10, "80", "김철수", 50, 50.6]
b=a.index("80")
a.pop(b)
a

['hi', 10, '김철수', 50, 50.6]

In [120]:
import numpy as np

In [121]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [122]:
a=np.append(a,[4,5])
a

array([1, 2, 3, 4, 4, 5])

In [123]:
a=np.insert(a, 1, [7,8])
a

array([1, 7, 8, 2, 3, 4, 4, 5])

In [124]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [125]:
a=np.delete(a, [1,3])

In [126]:
a= a[a<=4]
a

array([1, 3])

In [127]:
a= a[a!=4]
a

array([1, 3])

In [128]:
array1 = np.array([[1,2], [3,4]])
array2 = np.array([[5,6], [7,8]])
merged_array = np.vstack((array1, array2))
print(merged_array)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

In [129]:
array1 = np.array([[1,2], [3,4]])
array2 = np.array([[5,6], [7,8]])
merged_array = np.hstack((array1, array2))
print(merged_array)

[[1 2 5 6]
 [3 4 7 8]]

In [130]:
A={1:"김철수", 20:"박영희"}

In [131]:
A[1]

'김철수'

In [145]:
#(오류문제)
A[2]

KeyError: 2

In [133]:
A.get(1)

'김철수'

In [134]:
A.get(3)

In [135]:
A={"1-A":"김철수", "20-B":"박영희"}

In [136]:
A["1-A"]

'김철수'

In [137]:
A["20-B"]

'박영희'

In [138]:
A.get("1-A")

'김철수'

In [139]:
A.get("20-B")

'박영희'

In [140]:
A={"1-A":"김철수", "20-B":"박영희"}
A["2-A"] = "영희"
A

{'1-A': '김철수', '20-B': '박영희', '2-A': '영희'}

In [141]:
A={
    "1-A":[1,2,3,4,5],
    "20-B":["A","B","C","D","E"]
}
A

{'1-A': [1, 2, 3, 4, 5], '20-B': ['A', 'B', 'C', 'D', 'E']}

In [144]:
#(문제)

In [190]:
#1
a = [10, 20, 30, [1,2,3]]

In [191]:
#2
print(a[3])

[1, 2, 3]

In [239]:
#3
수학점수=[20,30,40,50,60]
영어점수=[50,70,50,60,90]

In [240]:
#4
url = "https://www.youtube.com/"
str = url.replace("https://www.youtube.com/","www.naver.com")
print(str)

www.naver.com

In [241]:
#5
수학점수 = [20,30,40,50,60]
영어점수 = [50,70,50,60,90]

수학점수_평균 = sum(수학점수)/len(수학점수)
영어점수_평균 = sum(영어점수)/len(영어점수)

print("수학평균:", 수학점수_평균)
print("영어평균:", 영어점수_평균)

수학평균: 40.0
영어평균: 64.0

In [242]:
#6
a = [1,2,100,4,5,900]
a.pop(2)
a.pop(-1)
a

[1, 2, 4, 5]

In [243]:
#7
A={"수학점수" : [20, 30, 40, 50, 60], "영어점수" : [50, 70, 50 , 60, 90]}

In [244]:
#8
A["수학점수"][0] + A["영어점수"][2]

70

In [245]:
#(6주차)

In [357]:
import pandas as pd

In [358]:
data={
        'Name': ['Alice', 'Bob', 'Charlie'],
        'Age' : [25, 30, 35],
        'City' : ['New York', 'Paris', 'London'],
}

In [359]:
print(data)

{'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35], 'City': ['New York', 'Paris', 'London']}

In [360]:
df = pd.DataFrame(data)

In [361]:
print(df)

      Name  Age      City
0    Alice   25  New York
1      Bob   30     Paris
2  Charlie   35    London

In [362]:
import numpy as np
data = np.array([
    [1,'Alice',30],
    [2,'Bob',25],
    [3,'Charlie', 35]
])

In [363]:
print(data)

[['1' 'Alice' '30']
 ['2' 'Bob' '25']
 ['3' 'Charlie' '35']]

In [364]:
df = pd.DataFrame(data)

In [365]:
df = pd.DataFrame(data, columns=['ID','Name','Age'])

In [366]:
df = pd.read_csv("C:/Users/USER/Desktop/국영수.csv",header=0, encoding ='cp949')

In [367]:
df_h = pd.read_csv("C:/Users/USER/Desktop/국영수.csv",header=0, encoding ='cp949')

In [368]:
print(df)

   국어  영어  수학 체육
0  50  88  21  상
1  41  87  54  중
2  85  65  84  상
3  61  85  13  중
4  54  41  21  하
5  84  47  87  하
6  77  98  65  상
7  87  58  54  중
8  54  22  78  히

In [369]:
df_nh = pd.read_csv("C:/Users/USER/Desktop/국영수.csv",header=None, encoding ='cp949')

In [370]:
df.shape

(9, 4)

In [371]:
df.columns

Index(['국어', '영어', '수학', '체육'], dtype='object')

In [372]:
df.dtypes

국어     int64
영어     int64
수학     int64
체육    object
dtype: object

In [373]:
df.describe()

              국어         영어         수학
count   9.000000   9.000000   9.000000
mean   65.888889  65.666667  53.000000
std    17.467430  25.729361  28.583212
min    41.000000  22.000000  13.000000
25%    54.000000  47.000000  21.000000
50%    61.000000  65.000000  54.000000
75%    84.000000  87.000000  78.000000
max    87.000000  98.000000  87.000000

In [374]:
df.head()

   국어  영어  수학 체육
0  50  88  21  상
1  41  87  54  중
2  85  65  84  상
3  61  85  13  중
4  54  41  21  하

In [375]:
df.tail()

   국어  영어  수학 체육
4  54  41  21  하
5  84  47  87  하
6  77  98  65  상
7  87  58  54  중
8  54  22  78  히

In [376]:
df.isnull().sum()

국어    0
영어    0
수학    0
체육    0
dtype: int64

In [377]:
df['체육'].value_counts()

체육
상    3
중    3
하    2
히    1
Name: count, dtype: int64

In [378]:
df['체육'].unique()

array(['상', '중', '하', '히'], dtype=object)

In [379]:
df['체육'].nunique()

4

In [380]:
df["합계"]=df["국어"]+df["영어"]

In [381]:
df

   국어  영어  수학 체육   합계
0  50  88  21  상  138
1  41  87  54  중  128
2  85  65  84  상  150
3  61  85  13  중  146
4  54  41  21  하   95
5  84  47  87  하  131
6  77  98  65  상  175
7  87  58  54  중  145
8  54  22  78  히   76

In [382]:
columns=['국어', '영어', '수학']

In [383]:
selected_columns=df[columns]
selected_columns

   국어  영어  수학
0  50  88  21
1  41  87  54
2  85  65  84
3  61  85  13
4  54  41  21
5  84  47  87
6  77  98  65
7  87  58  54
8  54  22  78

In [384]:
df.loc[:,"수학"]

0    21
1    54
2    84
3    13
4    21
5    87
6    65
7    54
8    78
Name: 수학, dtype: int64

In [385]:
columns=['국어', '영어', '수학']
selected_columns=df.loc[:,columns]

In [386]:
df=df.drop(['체육'], axis=1)

In [387]:
df

   국어  영어  수학   합계
0  50  88  21  138
1  41  87  54  128
2  85  65  84  150
3  61  85  13  146
4  54  41  21   95
5  84  47  87  131
6  77  98  65  175
7  87  58  54  145
8  54  22  78   76

In [388]:
data={
        'A': [1,2,3,4],
        'B' : [4.1, 3.5, 2.1, 5.7],
        'C' : ['one', 'two', 'three', 'four'],
}

In [389]:
df=pd.DataFrame(data)

In [390]:
df['A'] = df['A'].astype(float)
df['A'].dtype

dtype('float64')

In [391]:
df['B'] = df['B'].astype(int)
df['B'].dtype

dtype('int64')

In [392]:
df['A'] = df['A'].astype('str')
df['A'].dtype

dtype('O')

In [393]:
df['C'] = df['C'].astype('category')
df['C'].dtype

CategoricalDtype(categories=['four', 'one', 'three', 'two'], ordered=False, categories_dtype=object)

In [394]:
#숫자를 문자열로 바꿀 순 있지만 문자열을 다시 숫자로 바꾸면 오류 발생

In [395]:
df = df.rename(columns={
        'A':'국어',
        'B':'영어',
        'C':'수학',
})

In [396]:
df

    국어  영어     수학
0  1.0   4    one
1  2.0   3    two
2  3.0   2  three
3  4.0   5   four

In [397]:
data = {
    'Numeric1':[1,np.nan,3,4],
    'Numeric2':[5,6,np.nan,8.2],
    'Category':['dog', np.nan, 'cat','dog']
    }

In [398]:
df=pd.DataFrame(data)

In [399]:
A=df.select_dtypes(include=["number"]).columns
df[A]

   Numeric1  Numeric2
0       1.0       5.0
1       NaN       6.0
2       3.0       NaN
3       4.0       8.2

In [400]:
B=df.select_dtypes(include=['object', 'category']).columns
df[B]

  Category
0      dog
1      NaN
2      cat
3      dog

In [401]:
df[A].fillna(df[A].median())

   Numeric1  Numeric2
0       1.0       5.0
1       3.0       6.0
2       3.0       6.0
3       4.0       8.2

In [402]:
df[A].fillna(df[A].mean())

   Numeric1  Numeric2
0  1.000000       5.0
1  2.666667       6.0
2  3.000000       6.4
3  4.000000       8.2

In [403]:
df1= pd.DataFrame({
    'a':['a0','a1','a2','a3'],
    'b':['b0','b1','b2','b3'],
    'c':['c0','c1','c2','c3'],
})

df2= pd.DataFrame({
    'a':['a2','a3','a4','a5'],
    'b':['b2','b3','b4','b5'],
    'c':['c2','c3','c4','c5'],
    'd':['d2','d3','d4','d5'],
})

In [404]:
pd.concat([df1,df2],axis=0) #행기준

    a   b   c    d
0  a0  b0  c0  NaN
1  a1  b1  c1  NaN
2  a2  b2  c2  NaN
3  a3  b3  c3  NaN
0  a2  b2  c2   d2
1  a3  b3  c3   d3
2  a4  b4  c4   d4
3  a5  b5  c5   d5

In [405]:
pd.concat([df1,df2],axis=1) #열기준

    a   b   c   a   b   c   d
0  a0  b0  c0  a2  b2  c2  d2
1  a1  b1  c1  a3  b3  c3  d3
2  a2  b2  c2  a4  b4  c4  d4
3  a3  b3  c3  a5  b5  c5  d5

In [406]:
pd.concat([df[A], df[B]],axis=1)

   Numeric1  Numeric2 Category
0       1.0       5.0      dog
1       NaN       6.0      NaN
2       3.0       NaN      cat
3       4.0       8.2      dog

In [407]:
df[(df['Numeric2']>=6) & (df['Numeric2']<=10)]

   Numeric1  Numeric2 Category
1       NaN       6.0      NaN
3       4.0       8.2      dog

In [408]:
df[(df['Numeric2']>=6)|(df['Numeric2']<=10)]

   Numeric1  Numeric2 Category
0       1.0       5.0      dog
1       NaN       6.0      NaN
3       4.0       8.2      dog